//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Bordro = new HashSet<Bordro>();
            this.Loglar = new HashSet<Loglar>();
            this.PersonelDokuman = new HashSet<PersonelDokuman>();
        }
    
        public int PersonelId { get; set; }
        public int SicilNo { get; set; }
        public string TcNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Cep { get; set; }
        public string Eposta { get; set; }
        public string Adres { get; set; }
        public string Sifre { get; set; }
        public Nullable<double> YillikIzin { get; set; }
        public double Maas { get; set; }
        public string OzelSaglik { get; set; }
        public string KanGrubu { get; set; }
        public System.DateTime IseGiris { get; set; }
        public Nullable<System.DateTime> IstenCikis { get; set; }
        public string Durum { get; set; }
        public int BolumId { get; set; }
        public int GorevId { get; set; }
        public int RolId { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bordro> Bordro { get; set; }
        public virtual Gorev Gorev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loglar> Loglar { get; set; }
        public virtual Roller Roller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelDokuman> PersonelDokuman { get; set; }
    }
}
