//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYSProjeWinUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bordro
    {
        public int BordroId { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<double> HiMesai { get; set; }
        public Nullable<double> HsMesai { get; set; }
        public Nullable<double> Prim { get; set; }
        public double SaatUcret { get; set; }
        public double CalistigiGun { get; set; }
        public double Ucret { get; set; }
        public int PersonelId { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
