//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYSProjeWinUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IKYSProjeEntities : DbContext
    {
        public IKYSProjeEntities()
            : base("name=IKYSProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolum> Bolum { get; set; }
        public virtual DbSet<Bordro> Bordro { get; set; }
        public virtual DbSet<Gorev> Gorev { get; set; }
        public virtual DbSet<KDKategori> KDKategori { get; set; }
        public virtual DbSet<KurumsalDokuman> KurumsalDokuman { get; set; }
        public virtual DbSet<Loglar> Loglar { get; set; }
        public virtual DbSet<PDKategori> PDKategori { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<PersonelDokuman> PersonelDokuman { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<Sirket> Sirket { get; set; }
    }
}
