//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYSProjeWinUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int LogId { get; set; }
        public string Eylem { get; set; }
        public string Modul { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime Tarih { get; set; }
        public int PersonelId { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
