//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYSProjeWinUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelDokuman
    {
        public int PdId { get; set; }
        public string PdPath { get; set; }
        public int PersonelId { get; set; }
        public int PDKId { get; set; }
    
        public virtual PDKategori PDKategori { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
