//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYSProjeWinUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelId { get; set; }
        public int SicilNo { get; set; }
        public string TcNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Cep1 { get; set; }
        public string Cep2 { get; set; }
        public string Eposta1 { get; set; }
        public string Eposta2 { get; set; }
        public string Adres { get; set; }
        public string Sifre { get; set; }
        public Nullable<double> YillikIzin { get; set; }
        public double Maas { get; set; }
        public string OzelSaglik { get; set; }
        public string KanGrubu { get; set; }
        public System.DateTime IseGiris { get; set; }
        public Nullable<System.DateTime> IstenCikis { get; set; }
        public string Durum { get; set; }
        public int BolumId { get; set; }
        public int GorevId { get; set; }
        public int RolId { get; set; }
    }
}
