//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYSProjeWinUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirket
    {
        public int SirketId { get; set; }
        public string Unvan { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string VergiDairesiAdi { get; set; }
        public string VergiDairesiNo { get; set; }
    }
}
